parameters:
  terraformVersion: ''
  ServiceAWS: '' 
  BucketName: ''
  Key: ''
  environmentServiceNameAWS: ''
  
jobs:
  - job: TerraformInit
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: ${{ parameters.terraformVersion }}
    - script: |
        sed -i 's/TOKEN/$(TOKEN)/' main.tf
        cp backend/sandbox sandbox.tf
    - task: TerraformTaskV1@0
      displayName: "Sandbox init"
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: ${{ parameters.ServiceAWS }}
        backendAWSBucketName: ${{ parameters.BucketName }}
        backendAWSKey: ${{ parameters.Key }}
    - task: TerraformTaskV1@0
      displayName: "Terraform Plan"
      inputs:
        provider: 'aws'
        command: 'plan'
        commandOptions: '-var-file vars/terraform.sandbox.tfvars -out=tfplan'
        environmentServiceNameAWS: ${{ parameters.environmentServiceNameAWS }
